name: "Test action"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use this action
        uses: ./
      - name: Setup Java
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 8
      - name: Check if JAR executes correctly
        if: runner.os != 'windows'
        run: |
          java -jar $Antlr4ToolPath
      - name: Check if JAR executes correctly (Windows)
        if: runner.os == 'windows'
        run: |
          java -jar $Env:Antlr4ToolPath
